return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "BufReadPre",
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "apex",
        "bash",
        "c",
        "css",
        "dockerfile",
        "git_config",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "php",
        "python",
        "query",
        "rbs",
        "ruby",
        "rust",
        "scala",
        "scss",
        "sql",
        "terraform",
        "tmux",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
      },
      modules = {},
      sync_install = false,
      auto_install = true,
      ignore_install = {},
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
