return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  lazy = true,
  event = { "BufReadPre" },
  config = function()
    require('nvim-treesitter.configs').setup {
      ensure_installed = {
        "bash",
        "c",
        "css",
        "dockerfile",
        "git_config",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "python",
        "query",
        "rbs",
        "ruby",
        "rust",
        "scala",
        "scss",
        "sql",
        "terraform",
        "tmux",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
      },
      highlight = { enable = true },
      indent = { enable = true },
    }
  end
}
